spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tamnaradb?serverTimezone=UTC
    username: admin
    password: tamnarapwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      mode: always

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

# swagger setting
springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: false


jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

